### ISSUE TITLE
bug: Additions Rules work erratically

### ISSUE THREAD

**Issue by cennydavidsson** [maor-rozenfeld/prlint-reloaded#2]
The rules for additions seems not to work correctly, sometimes it works as expected and sometimes not.

I've tried and verified this regular expression and can't find any problems with it. 

```javascript
{
  "additions": [
    {
      "pattern": "^([0-9]|[1-9][0-9]|[1-4][0-9][0-9]|[5][0][0])$",
      "message": "Your PR is too big (over 500 additions)"
    }
  ]
}
```

Also tried this and didn't work:
```javascript
{
  "additions": [
    {
      "pattern": /^([0-9]|[1-9][0-9]|[1-4][0-9][0-9]|[5][0][0])$/,
      "message": "Your PR is too big (over 500 additions)"
    }
  ]
}
```

**Comment by yellowblood** [comment]
Maybe the expressions don't work on numeric fields. If you provide a fix I will deploy it.

**Comment by maor-rozenfeld** [comment]
The repo was converted into a GitHub Action, and it now only supports the PR title.
